import type { FinancialProfile, PastPurchase, Product } from "./types";

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "smartphone",
    name: "Galaxy S-series 5G (256GB)",
    brand: "Samsung",
    category: "Smartphone",
    price: 34999,
    mrp: 49999,
    typicalPrice: 31200,
    fairPriceLow: 28500,
    fairPriceHigh: 32000,
    refurbPrice: 26999,
    usedPrice: 22000,
    resaleAfter1Year: 21000,
    lifetimeYears: 4,
    refreshSoon: true,
    discountFrequency: "high",
    offerText: "30% OFF · Only 2 left · Sale ends in 10 minutes",
    envImpactNew: "High",
    emoji: "📱",
    specs: ["6.5\" AMOLED 120Hz", "8GB / 256GB", "5000mAh"],
  },
  {
    id: "laptop",
    name: "Ryzen 7 Thin & Light Laptop",
    brand: "Lenovo",
    category: "Laptop",
    price: 62999,
    mrp: 79999,
    typicalPrice: 67500,
    fairPriceLow: 62000,
    fairPriceHigh: 70000,
    refurbPrice: 57999,
    usedPrice: 46000,
    resaleAfter1Year: 40000,
    lifetimeYears: 5,
    discountFrequency: "medium",
    offerText: "Limited-period festive price",
    envImpactNew: "High",
    emoji: "💻",
    specs: ["Ryzen 7 · 16GB RAM", "1TB SSD", "14\" 2.8K OLED"],
  },
  {
    id: "headphones",
    name: "WH-1000XM5 Noise Cancelling",
    brand: "Sony",
    category: "Headphones",
    price: 29999,
    mrp: 34990,
    typicalPrice: 28400,
    fairPriceLow: 24000,
    fairPriceHigh: 28000,
    refurbPrice: 19999,
    usedPrice: 16500,
    resaleAfter1Year: 14000,
    lifetimeYears: 4,
    discountFrequency: "high",
    envImpactNew: "Medium",
    emoji: "🎧",
    specs: ["Industry-leading ANC", "30h battery", "Multipoint"],
  },
  {
    id: "camera",
    name: "Mirrorless Camera + 18-50mm Kit",
    brand: "Canon",
    category: "Camera",
    price: 74999,
    mrp: 89999,
    typicalPrice: 78500,
    fairPriceLow: 72000,
    fairPriceHigh: 80000,
    refurbPrice: 64999,
    usedPrice: 52000,
    rentPerUse: 1500,
    repairCost: 6500,
    resaleAfter1Year: 55000,
    lifetimeYears: 7,
    discountFrequency: "low",
    envImpactNew: "Medium",
    emoji: "📷",
    specs: ["24MP APS-C", "4K 30fps", "In-body stabilisation"],
  },
  {
    id: "projector",
    name: "1080p Smart Home Projector",
    brand: "BenQ",
    category: "Projector",
    price: 12499,
    mrp: 17999,
    typicalPrice: 12100,
    fairPriceLow: 10500,
    fairPriceHigh: 12500,
    refurbPrice: 9499,
    usedPrice: 7500,
    rentPerUse: 700,
    repairCost: 2500,
    resaleAfter1Year: 6500,
    lifetimeYears: 4,
    discountFrequency: "medium",
    offerText: "Deal of the day · 20 people viewing this",
    envImpactNew: "Medium",
    emoji: "📽️",
    specs: ["1080p · 550 ANSI", "Android TV built-in", "Auto keystone"],
  },
  {
    id: "smartwatch",
    name: "Smartwatch Pro (AMOLED)",
    brand: "Noise",
    category: "Smartwatch",
    price: 8999,
    mrp: 12999,
    typicalPrice: 7600,
    fairPriceLow: 6500,
    fairPriceHigh: 7800,
    refurbPrice: 6299,
    usedPrice: 4800,
    repairCost: 1200,
    resaleAfter1Year: 3200,
    lifetimeYears: 3,
    discountFrequency: "high",
    offerText: "Flat 31% off · Ends tonight",
    envImpactNew: "Medium",
    emoji: "⌚",
    specs: ["1.8\" AMOLED", "BT calling", "7-day battery"],
  },
];

export const DEMO_PROFILE: FinancialProfile = {
  income: 35000,
  essentials: 18000,
  discretionary: 7000,
  savings: 60000,
  goal: "Buy a laptop in 6 months",
  monthlyShopping: 4500,
  demo: true,
};

export const DEMO_HISTORY: PastPurchase[] = [
  { id: "p1", name: "Smartphone (128GB)", category: "Smartphone", price: 45000, monthsAgo: 11 },
  { id: "p2", name: "Wireless headphones", category: "Headphones", price: 3000, monthsAgo: 6 },
  { id: "p3", name: "Smartwatch", category: "Smartwatch", price: 2500, monthsAgo: 4 },
  { id: "p4", name: "Running shoes", category: "Footwear", price: 5000, monthsAgo: 2 },
];

export function findDemoProduct(query: string): Product | undefined {
  const q = query.toLowerCase();
  return (
    DEMO_PRODUCTS.find((p) => q.includes(p.id)) ??
    DEMO_PRODUCTS.find((p) => q.includes(p.category.toLowerCase())) ??
    DEMO_PRODUCTS.find(
      (p) => q.includes(p.brand.toLowerCase()) || p.name.toLowerCase().includes(q),
    )
  );
}
